node-cache-key: &node-cache-key node-v2-{{ checksum "package.json" }}
node-docker-image: &node-docker-image circleci/node:12.11

version: 2.1

executors:
  node_executor:
    docker:
      - image: *node-docker-image

commands:
  node_bootstrap:
    description: Checkout code and restore node cache
    steps:
      - checkout
      - restore_cache:
          keys:
            - *node-cache-key
            - node-v2-
  login_github_package_registry:
    description: Adds token for accessing github package registry
    steps:
      - run:
          name: Login to github package registry
          command: . .circleci/login_github_package_registry.sh

jobs:
  bootstrap:
    description: Install node modules
    executor: node_executor
    steps:
      - node_bootstrap
      - login_github_package_registry
      - run: npm install
      - save_cache:
          key: *node-cache-key
          paths:
            - node_modules

  lint:
    description: Run the linter
    executor: node_executor
    steps:
      - node_bootstrap
      - run: npm runt lint

  test:
    description: Run tests
    executor: node_executor
    steps:
      - node_bootstrap
      - run: npm runt test:ci

  build_push:
    description: Build docker image and push it
    executor: node_executor
    steps:
      - checkout
      - login_github_package_registry
      - setup_remote_docker:
          version: 18.09.3
      - run: npm run docker:build
      - run: echo "$DOCKER_TOKEN" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin
      - run: npm run docker:push

workflows:
  version: 2
  commit:
    jobs:
      - bootstrap
      - lint:
          requires:
            - bootstrap
      - test:
          requires:
            - bootstrap
      - build_push:
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - master
